language: java
jdk: openjdk14

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `timesheet-mgmt-system`;
              CREATE USER "mango"@"localhost" IDENTIFIED BY "TropicalKing#2020";
              GRANT ALL PRIVILEGES ON `timesheet-mgmt-system`.* TO "mango"@"localhost";'